### ISSUE TITLE
support multiple nodes or artnet broadcast

### ISSUE THREAD

**Issue by bauersimon** [bauersimon/ScreenToArtNet#6]
# Summary
Currently only targeting one ArtNet node is supported.

# Tasks
- [ ] support multiple nodes
- [ ] support artnet broadcast

**Comment by LoneWalkerWolf** [comment]
I believe ArtNet broadcast is supported, as I am currently using it. :) 
Just enter 255.255.255.255 in the "destination" field.

**Comment by bauersimon** [comment]
Oh nice - thanks for the info! I cannot test this myself at the moment but if the go artnet library supports it out of the box, we can close this. I guess we can always re-open.
